//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Recursos.Controller
{
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SitioWeb.Recursos.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente Experimentado.
        /// </summary>
        public static string Agente_Experimentado {
            get {
                return ResourceManager.GetString("Agente Experimentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALQUILER.
        /// </summary>
        public static string ALQUILER {
            get {
                return ResourceManager.GetString("ALQUILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apartamento de lujo.
        /// </summary>
        public static string Apartamento_de_lujo {
            get {
                return ResourceManager.GetString("Apartamento de lujo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apartamento interior.
        /// </summary>
        public static string Apartamento_interior {
            get {
                return ResourceManager.GetString("Apartamento interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenidos a Sol y Luna Real Estate.
        /// </summary>
        public static string BienvenidosASolYLunaRealEstate {
            get {
                return ResourceManager.GetString("BienvenidosASolYLunaRealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brindamos los mejores   Servicios Inmobiliarios.
        /// </summary>
        public static string Brindamos_los_mejores___Servicios_Inmobiliarios {
            get {
                return ResourceManager.GetString("Brindamos los mejores   Servicios Inmobiliarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Propiedad.
        /// </summary>
        public static string Buscar_Propiedad {
            get {
                return ResourceManager.GetString("Buscar Propiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busca por provincias, canton o distrito.
        /// </summary>
        public static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casa de diseño Monall.
        /// </summary>
        public static string Casa_de_diseño_Monall {
            get {
                return ResourceManager.GetString("Casa de diseño Monall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casas Amuebladas.
        /// </summary>
        public static string Casas_Amuebladas {
            get {
                return ResourceManager.GetString("Casas Amuebladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Como puedes vender o alquilar tu propiedad con nosotros.
        /// </summary>
        public static string Como_puedes_vender_o_alquilar_tu_propiedad_con_nosotros {
            get {
                return ResourceManager.GetString("Como puedes vender o alquilar tu propiedad con nosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPRA.
        /// </summary>
        public static string COMPRA {
            get {
                return ResourceManager.GetString("COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a comprar.
        /// </summary>
        public static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTACTANOS.
        /// </summary>
        public static string CONTACTANOS {
            get {
                return ResourceManager.GetString("CONTACTANOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contamos con una alta gama de propiedades para tus gustos.
        /// </summary>
        public static string Contamos_con_una_alta_gama_de_propiedades_para_tus_gustos {
            get {
                return ResourceManager.GetString("Contamos con una alta gama de propiedades para tus gustos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destacados.
        /// </summary>
        public static string Destacados {
            get {
                return ResourceManager.GetString("Destacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es obligatorio.
        /// </summary>
        public static string El_campo__0__es_obligatorio {
            get {
                return ResourceManager.GetString("El campo {0} es obligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En alquiler.
        /// </summary>
        public static string En_alquiler {
            get {
                return ResourceManager.GetString("En alquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En venta.
        /// </summary>
        public static string En_venta {
            get {
                return ResourceManager.GetString("En venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra tu propiedad en Costa Rica.
        /// </summary>
        public static string Encuentra_tu_propiedad_en_Costa_Rica {
            get {
                return ResourceManager.GetString("Encuentra tu propiedad en Costa Rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentre la casa de sus sueños.
        /// </summary>
        public static string Encuentre_la_casa_de_sus_sueños {
            get {
                return ResourceManager.GetString("Encuentre la casa de sus sueños", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESCRIBENOS.
        /// </summary>
        public static string ESCRIBENOS {
            get {
                return ResourceManager.GetString("ESCRIBENOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explora las ultimas ofertas.
        /// </summary>
        public static string Explora_las_ultimas_ofertas {
            get {
                return ResourceManager.GetString("Explora las ultimas ofertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string Iniciar_Sesión {
            get {
                return ResourceManager.GetString("Iniciar Sesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locales Comerciales.
        /// </summary>
        public static string Locales_Comerciales {
            get {
                return ResourceManager.GetString("Locales Comerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nosotros.
        /// </summary>
        public static string Nosotros {
            get {
                return ResourceManager.GetString("Nosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVAS PROPIEDADES.
        /// </summary>
        public static string NUEVAS_PROPIEDADES {
            get {
                return ResourceManager.GetString("NUEVAS PROPIEDADES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso.
        /// </summary>
        public static string Paso {
            get {
                return ResourceManager.GetString("Paso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a propiedades.
        /// </summary>
        public static string Propiedades {
            get {
                return ResourceManager.GetString("Propiedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Playa.
        /// </summary>
        public static string Propiedades_de_Playa {
            get {
                return ResourceManager.GetString("Propiedades de Playa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades Rurales.
        /// </summary>
        public static string Propiedades_Rurales {
            get {
                return ResourceManager.GetString("Propiedades Rurales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicamos tu Propiedad.
        /// </summary>
        public static string Publicamos_tu_Propiedad {
            get {
                return ResourceManager.GetString("Publicamos tu Propiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Que estás buscando?.
        /// </summary>
        public static string Que_estás_buscando_ {
            get {
                return ResourceManager.GetString("Que estás buscando?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Sol y Luna Real Estate.
        /// </summary>
        public static string Saludo {
            get {
                return ResourceManager.GetString("Saludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string Servicios {
            get {
                return ResourceManager.GetString("Servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios Inmobiliarios de confianza y seguridad.
        /// </summary>
        public static string Servicios_Inmobiliarios_de_confianza_y_seguridad {
            get {
                return ResourceManager.GetString("Servicios Inmobiliarios de confianza y seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sigue estos sencillos pasos.
        /// </summary>
        public static string Sigue_estos__br____sencillos_pasos {
            get {
                return ResourceManager.GetString("Sigue estos <br /> sencillos pasos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afirmamos el compromiso con nuestros clientes contando con el personal mejor calificado.
        /// </summary>
        public static string Texto_Agente_experimentado {
            get {
                return ResourceManager.GetString("Texto Agente experimentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Despreocupate por el proceso, nosotros te lo facilitamos, vende, compra o alquina por medio de nosotros.
        /// </summary>
        public static string Texto_publicamos_propiedad {
            get {
                return ResourceManager.GetString("Texto publicamos propiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu lo solicitas, nosotros lo efectuamos. Contamos con una amplia lista de clientes tanto compradores como propietarios.
        /// </summary>
        public static string Tu_lo_solicitas__nosotros_lo_efectuamos__Contamos_con_una_amplia_lista_de_clientes_tanto_compradores_como_propietarios {
            get {
                return ResourceManager.GetString("Tu lo solicitas, nosotros lo efectuamos. Contamos con una amplia lista de cliente" +
                        "s tanto compradores como propietarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vender.
        /// </summary>
        public static string Vender {
            get {
                return ResourceManager.GetString("Vender", resourceCulture);
            }
        }
    }
}
